INSERT INTO docstatus (name, description, active, created_at, updated_at) VALUES
('Applicable', 'Document is applicable and can be used', 1, NOW(), NOW()),
('Suspended', 'Document is temporarily suspended', 1, NOW(), NOW()),
('Replaced', 'Document has been replaced by a newer version', 1, NOW(), NOW()),
('Cancelled', 'Document has been canceled', 1, NOW(), NOW()),
('In Progress', 'Document is currently in progress', 1, NOW(), NOW()),
('Valid', 'Document is valid and active', 1, NOW(), NOW()),
('Rejected', 'Document has been rejected', 1, NOW(), NOW()),
('Rental', 'Document is related to rental', 1, NOW(), NOW()),
('Solid', 'Document is solid/permanent', 1, NOW(), NOW()),
('Free', 'Document is free/available', 1, NOW(), NOW()),
('Expired', 'Document has expired', 1, NOW(), NOW());


INSERT INTO countries (name, active, created_at) VALUES
('Afghanistan', true, NOW()),
('Albania', true, NOW()),
('Algeria', true, NOW()),
('Andorra', true, NOW()),
('Angola', true, NOW()),
('Antigua and Barbuda', true, NOW()),
('Argentina', true, NOW()),
('Armenia', true, NOW()),
('Australia', true, NOW()),
('Austria', true, NOW()),
('Azerbaijan', true, NOW()),
('Bahamas', true, NOW()),
('Bahrain', true, NOW()),
('Bangladesh', true, NOW()),
('Barbados', true, NOW()),
('Belarus', true, NOW()),
('Belgium', true, NOW()),
('Belize', true, NOW()),
('Benin', true, NOW()),
('Bhutan', true, NOW()),
('Bolivia', true, NOW()),
('Bosnia and Herzegovina', true, NOW()),
('Botswana', true, NOW()),
('Brazil', true, NOW()),
('Brunei', true, NOW()),
('Bulgaria', true, NOW()),
('Burkina Faso', true, NOW()),
('Burundi', true, NOW()),
('Cabo Verde', true, NOW()),
('Cambodia', true, NOW()),
('Cameroon', true, NOW()),
('Canada', true, NOW()),
('Central African Republic', true, NOW()),
('Chad', true, NOW()),
('Chile', true, NOW()),
('China', true, NOW()),
('Colombia', true, NOW()),
('Comoros', true, NOW()),
('Congo (Congo-Brazzaville)', true, NOW()),
('Costa Rica', true, NOW()),
('Croatia', true, NOW()),
('Cuba', true, NOW()),
('Cyprus', true, NOW()),
('Czech Republic (Czechia)', true, NOW()),
('Democratic Republic of the Congo', true, NOW()),
('Denmark', true, NOW()),
('Djibouti', true, NOW()),
('Dominica', true, NOW()),
('Dominican Republic', true, NOW()),
('Ecuador', true, NOW()),
('Egypt', true, NOW()),
('El Salvador', true, NOW()),
('Equatorial Guinea', true, NOW()),
('Eritrea', true, NOW()),
('Estonia', true, NOW()),
('Eswatini (fmr. Swaziland)', true, NOW()),
('Ethiopia', true, NOW()),
('Fiji', true, NOW()),
('Finland', true, NOW()),
('France', true, NOW()),
('Gabon', true, NOW()),
('Gambia', true, NOW()),
('Georgia', true, NOW()),
('Germany', true, NOW()),
('Ghana', true, NOW()),
('Greece', true, NOW()),
('Grenada', true, NOW()),
('Guatemala', true, NOW()),
('Guinea', true, NOW()),
('Guinea-Bissau', true, NOW()),
('Guyana', true, NOW()),
('Haiti', true, NOW()),
('Honduras', true, NOW()),
('Hungary', true, NOW()),
('Iceland', true, NOW()),
('India', true, NOW()),
('Indonesia', true, NOW()),
('Iran', true, NOW()),
('Iraq', true, NOW()),
('Ireland', true, NOW()),
('Israel', true, NOW()),
('Italy', true, NOW()),
('Jamaica', true, NOW()),
('Japan', true, NOW()),
('Jordan', true, NOW()),
('Kazakhstan', true, NOW()),
('Kenya', true, NOW()),
('Kiribati', true, NOW()),
('Kuwait', true, NOW()),
('Kyrgyzstan', true, NOW()),
('Laos', true, NOW()),
('Latvia', true, NOW()),
('Lebanon', true, NOW()),
('Lesotho', true, NOW()),
('Liberia', true, NOW()),
('Libya', true, NOW()),
('Liechtenstein', true, NOW()),
('Lithuania', true, NOW()),
('Luxembourg', true, NOW()),
('Madagascar', true, NOW()),
('Malawi', true, NOW()),
('Malaysia', true, NOW()),
('Maldives', true, NOW()),
('Mali', true, NOW()),
('Malta', true, NOW()),
('Marshall Islands', true, NOW()),
('Mauritania', true, NOW()),
('Mauritius', true, NOW()),
('Mexico', true, NOW()),
('Micronesia', true, NOW()),
('Moldova', true, NOW()),
('Monaco', true, NOW()),
('Mongolia', true, NOW()),
('Montenegro', true, NOW()),
('Morocco', true, NOW()),
('Mozambique', true, NOW()),
('Myanmar (Burma)', true, NOW()),
('Namibia', true, NOW()),
('Nauru', true, NOW()),
('Nepal', true, NOW()),
('Netherlands', true, NOW()),
('New Zealand', true, NOW()),
('Nicaragua', true, NOW()),
('Niger', true, NOW()),
('Nigeria', true, NOW()),
('North Korea', true, NOW()),
('North Macedonia', true, NOW()),
('Norway', true, NOW()),
('Oman', true, NOW()),
('Pakistan', true, NOW()),
('Palau', true, NOW()),
('Palestine State', true, NOW()),
('Panama', true, NOW()),
('Papua New Guinea', true, NOW()),
('Paraguay', true, NOW()),
('Peru', true, NOW()),
('Philippines', true, NOW()),
('Poland', true, NOW()),
('Portugal', true, NOW()),
('Qatar', true, NOW()),
('Romania', true, NOW()),
('Russia', true, NOW()),
('Rwanda', true, NOW()),
('Saint Kitts and Nevis', true, NOW()),
('Saint Lucia', true, NOW()),
('Saint Vincent and the Grenadines', true, NOW()),
('Samoa', true, NOW()),
('San Marino', true, NOW()),
('Sao Tome and Principe', true, NOW()),
('Saudi Arabia', true, NOW()),
('Senegal', true, NOW()),
('Serbia', true, NOW()),
('Seychelles', true, NOW()),
('Sierra Leone', true, NOW()),
('Singapore', true, NOW()),
('Slovakia', true, NOW()),
('Slovenia', true, NOW()),
('Solomon Islands', true, NOW()),
('Somalia', true, NOW()),
('South Africa', true, NOW()),
('South Korea', true, NOW()),
('South Sudan', true, NOW()),
('Spain', true, NOW()),
('Sri Lanka', true, NOW()),
('Sudan', true, NOW()),
('Suriname', true, NOW()),
('Sweden', true, NOW()),
('Switzerland', true, NOW()),
('Syria', true, NOW()),
('Taiwan', true, NOW()),
('Tajikistan', true, NOW()),
('Tanzania', true, NOW()),
('Thailand', true, NOW()),
('Timor-Leste', true, NOW()),
('Togo', true, NOW()),
('Tonga', true, NOW()),
('Trinidad and Tobago', true, NOW()),
('Tunisia', true, NOW()),
('Turkey', true, NOW()),
('Turkmenistan', true, NOW()),
('Tuvalu', true, NOW()),
('Uganda', true, NOW()),
('Ukraine', true, NOW()),
('United Arab Emirates', true, NOW()),
('United Kingdom', true, NOW()),
('United States of America', true, NOW()),
('Uruguay', true, NOW()),
('Uzbekistan', true, NOW()),
('Vanuatu', true, NOW()),
('Vatican City', true, NOW()),
('Venezuela', true, NOW()),
('Vietnam', true, NOW()),
('Yemen', true, NOW()),
('Zambia', true, NOW()),
('Zimbabwe', true, NOW());
